POST http://localhost:3000/documents
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="sample.pdf"
Content-Type: application/pdf

< ./fixtures/sample.pdf
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###############333
POST http://localhost:3000/documents/baad9df1-230c-4e14-aca1-a7511ade9498/index/semantic

#############
POST http://localhost:3000/documents/baad9df1-230c-4e14-aca1-a7511ade9498/debug/semantic-search
Content-Type: application/json

{
  "query":"Dónde aparece Morgan"
}

#########33
POST http://localhost:3000/documents/2d021e76-c377-4137-a93b-5233e2e7a67d/index/lexical

#############
POST http://localhost:3000/documents/2d021e76-c377-4137-a93b-5233e2e7a67d/debug/lexical-search
Content-Type: application/json

{
  "query":"Dónde aparece Morgan"
}