POST http://localhost:3000/documents
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="sample.pdf"
Content-Type: application/pdf

< ./fixtures/sample.pdf
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###############333
POST http://localhost:3000/documents/277f616c-a134-4789-b42c-53f9a6e8db12/index